## Tasca 4. Pràctica amb programació numèrica

In [1]:
import numpy as np
import pandas as pd

### Exercici 1
Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [2]:
def basic_stat(data):
    if data.ndim == 1:
        print(pd.DataFrame(data).describe())
    else:
        print("Error: La dimensió ha de ser 1")

In [3]:
basic_stat(np.array([3,4,5,23,4]))

               0
count   5.000000
mean    7.800000
std     8.526429
min     3.000000
25%     4.000000
50%     4.000000
75%     5.000000
max    23.000000


### Exercici 2
Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [4]:
def crea_matriu(n):
    return np.random.randint(0,101, size=(n,n))

In [5]:
crea_matriu(10)

array([[ 34,   5,   6,  93,  30,  58,  46,  34,  42,   7],
       [  1, 100,  96,  46,  53,   9,   9,  45,  40,  84],
       [ 88,  42,  14,   5,  13,  36,   1,  74,  80,   6],
       [  4,  77,  63,  31,  53,  29,  67,  23,  56,   4],
       [ 95,  89,  60,   7,  45,  98,  54,  89,  93,  81],
       [ 38,  94,   4,  25,  73,  76,  76,  73,  48,  66],
       [ 35,  64,  77,  41,  25,  22,  90,  61,  24,  24],
       [ 37,  55,  66,  60,  98,  36,  61,  30,  29,  44],
       [ 88,  97,  64,  21,   7,  87,  77,  96,  82,  23],
       [ 16,  32,   4,  72,  61,  40,  70,  42,  81,  26]])

### Exercici 3
Crea una funció que donada una taula de dues dimensions, et calculi els totals per fila i els totals per columna.

In [6]:
def sumes_totals(mat):
    if mat.ndim == 2:
        return (mat.sum(axis=0), mat.sum(axis=1))
    else:
        print("Error: La dimensió ha de ser 2")

In [7]:
a = np.random.randint(0, 9, size=(4,4))
a

array([[8, 8, 2, 3],
       [3, 0, 5, 1],
       [7, 7, 0, 5],
       [1, 1, 0, 3]])

In [8]:
col, files = sumes_totals(a)
print(f'La suma de les columnes es: {col}')
print(f'La suma de les files es: {files}')

La suma de les columnes es: [19 16  7 12]
La suma de les files es: [21  9 19  5]


### Exercici 4
Implementa manualment una funció que calculi el coeficient de correlació. Informa’t-en sobre els seus usos i interpretació.

In [23]:
np.corrcoef(np.random.randint(0,10,size=20),
            np.random.randint(0,10,size=20))    

array([[1.        , 0.53499681],
       [0.53499681, 1.        ]])